name: Update M-Sacco Progress Metrics

on:
  pull_request:
  push:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run Progress Script
        run: python scripts/update_progress.py
      - name: Commit metrics
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metrics/progress.json
          git commit -m "Update progress metrics"
          git push
